# Generated by Django 5.2.7 on 2025-10-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_assessmentrecord_certificaterecord_reportrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRecordActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10, verbose_name='Action')),
                ('flood_record_id', models.IntegerField(blank=True, null=True, verbose_name='Flood Record ID')),
                ('event_type', models.CharField(max_length=200, verbose_name='Event Type')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('affected_barangays', models.CharField(max_length=500, verbose_name='Affected Barangays')),
                ('casualties_dead', models.IntegerField(default=0, verbose_name='Deaths')),
                ('casualties_injured', models.IntegerField(default=0, verbose_name='Injured')),
                ('casualties_missing', models.IntegerField(default=0, verbose_name='Missing')),
                ('affected_persons', models.IntegerField(default=0, verbose_name='Affected Persons')),
                ('affected_families', models.IntegerField(default=0, verbose_name='Affected Families')),
                ('damage_total_php', models.FloatField(default=0, verbose_name='Total Damage (PHP)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Activity Date/Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Flood Record Activity',
                'verbose_name_plural': 'Flood Record Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
