# Generated by Django 5.2.7 on 2025-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_floodrecordactivity'),
    ]

    operations = [
    ]
