# Generated by Django 5.2.7 on 2025-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'timestamp'], name='users_login_usernam_9b9158_idx'), models.Index(fields=['ip_address', 'timestamp'], name='users_login_ip_addr_7c2b9b_idx')],
            },
        ),
    ]
