# Generated by Django 5.2.7 on 2025-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('operations', 'Operations'), ('planning', 'Planning'), ('logistics', 'Logistics'), ('admin', 'Administration'), ('other', 'Other')], default='other', max_length=20, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
