# Generated by Django 5.2.7 on 2025-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_bio_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Emergency Contact Number'),
        ),
    ]
