# Generated by Django 5.2.5 on 2025-11-15 06:31

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove the department field from the database.
    This field was removed from the model but still exists in the database,
    causing IntegrityError during user registration.
    """

    dependencies = [
        ('users', '0006_alter_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the department column if it exists
            sql='ALTER TABLE users_customuser DROP COLUMN IF EXISTS department;',
            reverse_sql='ALTER TABLE users_customuser ADD COLUMN department VARCHAR(100);'
        ),
    ]
