# Generated by Django 5.2.7 on 2025-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfalldata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tideleveldata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
        migrations.AddField(
            model_name='rainfalldata',
            name='station_name',
            field=models.CharField(default='Bacolod', max_length=100),
        ),
        migrations.AddField(
            model_name='tideleveldata',
            name='station_name',
            field=models.CharField(default='Bacolod', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station_name',
            field=models.CharField(default='Bacolod', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed_kph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
