# Generated by Django 5.2.5 on 2025-11-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_floodrecord_alter_rainfalldata_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
